[logs]
level = "info"
log_format ="%(asctime)s %(process)d %(levelname)s %(name)s %(message)s [%(funcName)s] %(pathname)s:%(lineno)d"
log_console = true
#log_dir = './logs'
#log_dir = '/var/log/logs/'
#log_file = ''
#stacklevel = 2